# Analyse Exploratoire

# Modélisation

### Import des modules

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np
pd.set_option("display.max_columns", 200)
#Selection
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV, 
    cross_validate,
    KFold
)
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error 
from sklearn.inspection import permutation_importance

#Preprocess
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

#Modèles
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

Import du dataset

In [9]:
df = pd.read_csv("../data/processed/dataset_clean_ghge.csv")
display(df)

,NumberofBuildings,NumberofFloors,PropertyGFAParking,ENERGYSTARScore,LogPropertyGFATotal,LogPropertyGFABuilding(s),LogLargestPropertyUseTypeGFA,LogGHGEmissionsIntensity,HasGas,HasSteam,Decennie,TotalPourcentGFAParking,TotalPourcentLargestProperty,BALLARD,Ballard,CENTRAL,Central,DELRIDGE,DELRIDGE NEIGHBORHOODS,DOWNTOWN,Delridge,EAST,GREATER DUWAMISH,LAKE UNION,MAGNOLIA / QUEEN ANNE,NORTH,NORTHEAST,NORTHWEST,North,Northwest,SOUTHEAST,SOUTHWEST,Distribution Center,Hospital,Hotel,K-12 School,Large Office,Low-Rise Multifamily,Medical Office,Mixed Use Property,Other,Refrigerated Warehouse,Retail Store,Senior Care Community,Small- and Mid-Sized Office,Supermarket / Grocery Store,Warehouse,Worship Facility,Adult Education,Automobile Dealership,Bank Branch,Courthouse,Data Center,Distribution Center.1,Financial Office,Fire Station,Fitness Center/Health Club/Gym,Food Service,Hospital (General Medical & Surgical),Hotel.1,K-12 School.1,Laboratory,Library,Lifestyle Center,Manufacturing/Industrial Plant,Medical Office.1,Movie Theater,Multifamily Housing,Museum,Non-Refrigerated Warehouse,Office,Other.1,Other - Education,Other - Entertainment/Public Assembly,Other - Lodging/Residential,Other - Mall,Other - Public Services,Other - Recreation,Other - Restaurant/Bar,Other - Services,Other - Utility,Other/Specialty Hospital,Parking,Performing Arts,"Personal Services (Health/Beauty, Dry Cleaning, etc)",Police Station,Pre-school/Daycare,Prison/Incarceration,Refrigerated Warehouse.1,"Repair Services (Vehicle, Shoe, Locksmith, etc)",Residence Hall/Dormitory,Residential Care Facility,Restaurant,Retail Store.1,Senior Care Community.1,Social/Meeting Hall,Strip Mall,Supermarket/Grocery Store,Urgent Care/Clinic/Other Outpatient,Wholesale Club/Supercenter,Worship Facility.1
0,1.0,12,0,60.0,11.390023,11.390023,11.390023,1.342865,1,1,1920,0.000000,100.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,11,15064,61.0,11.547974,11.390792,11.337154,1.350667,1,0,1990,14.545314,80.991831,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,41,196718,43.0,13.770629,13.540275,13.536450,1.160021,1,1,1960,20.574829,79.121963,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,10,0,56.0,11.023878,11.023878,11.023878,1.735189,1,1,1920,0.000000,100.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,18,62000,75.0,12.075856,11.640272,11.723559,1.355835,1,0,1980,35.311539,70.306983,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1420,1.0,1,0,72.0,9.812578,9.812578,9.812578,0.746688,1,0,1980,0.000000,100.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1421,1.0,1,0,72.0,9.680406,9.680406,9.680406,1.101940,1,0,2000,0.000000,100.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1422,1.0,1,0,72.0,9.484785,9.484785,8.933796,2.889816,1,0,1970,0.000000,57.634719,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1423,1.0,1,0,66.0,9.554072,9.554072,8.795128,0.943906,1,0,1980,0.000000,46.812283,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1424,1.0,1,0,66.0,9.812413,9.812413,9.020632,1.181727,1,0,1930,0.000000,45.300690,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Détails de la fonction permettant de tester et d'évaluer les modèles :
1. On entre les caractéristiques de notre validation croisées
- On divise le jeu en 5 fold
- On fixe un random_state pour pouvoir obtenir le même aléatoire pour nos différents tests
2. On définit nos métriques d'évaluation
- R2 :
- MAE :
- RMSE :
3. On entraine et teste le modèle selon les paramètres définies précédemment
4. On affiche les métriques d'évaluations du modèle

In [10]:
def modele_validation(modele, X, y):

    cv_details = KFold(n_splits=5, shuffle=True, random_state=42)
    
    scoring = ['r2', 'neg_mean_absolute_error', 'neg_root_mean_squared_error']

    cross_validation_result = cross_validate(modele, X, y, cv=cv_details, scoring=scoring, return_train_score=True)
    
    dict_resultats = {
        "R2": [np.mean(cross_validation_result["train_r2"]), np.mean(cross_validation_result["test_r2"])],
        "MAE": [-np.mean(cross_validation_result["train_neg_mean_absolute_error"]), -np.mean(cross_validation_result["test_neg_mean_absolute_error"])],
        "RMSE": [-np.mean(cross_validation_result["train_neg_root_mean_squared_error"]), -np.mean(cross_validation_result["test_neg_root_mean_squared_error"])],
        "Time (sec)": [np.mean(cross_validation_result["fit_time"]), np.mean(cross_validation_result["score_time"])]
    }
    
    df_visuel = pd.DataFrame(dict_resultats, index=["Train (Fit)", "Test (Score)"])
    display(df_visuel)

In [ ]:
# On définit notre variable cible
y = df["LogGHGEmissionsIntensity"]

# On créé 2 df sans variable cible et avec et sans EnergySTARSCORE
X = df.drop(columns=["LogGHGEmissionsIntensity"])

Test Regression linéaire avec et sans EnergyStarScore

In [ ]:
model = LinearRegression()

print("Résultat régression linéaire")
modele_validation(model, X, y)

Avec ENERGYSTARScore

                    R2       MAE      RMSE  Time (sec)
Train (Fit)   0.601039  0.262980  0.352149    0.021960
Test (Score)  0.474662  0.296656  0.402189    0.007781

Sans ENERGYSTARScore

                    R2       MAE      RMSE  Time (sec)
Train (Fit)   0.556727  0.277407  0.371167    0.018908
Test (Score)  0.427658  0.310936  0.419585    0.005771

Interprétation des résultats :
- Le modèle est plus performant en utilisant `ENERGYSTARScore` que sans
- Le modèle ne fait pas d'overfiting (test_R2 et train_R2 sont proches)
- Le modèle a un temps de fit et predict très rapide
- Le modèle peut faire des grosses erreurs (RMSE supérieur d'environ 16 points à MAE)

In [ ]:
model = RandomForestRegressor()

print("Résultat RandomForestRegressor")
modele_validation(model, X, y)

Avec ENERGYSTARScore

                    R2       MAE      RMSE  Time (sec)
Train (Fit)   0.931539  0.101577  0.145857    1.369125
Test (Score)  0.513368  0.271591  0.387090    0.020232

Sans ENERGYSTARScore

                    R2       MAE      RMSE  Time (sec)
Train (Fit)   0.927142  0.106470  0.150465    1.371743
Test (Score)  0.482717  0.283226  0.398754    0.021836

Interprétation des résultats : 
- Ici notre modèle fait clairement de l'overfitting
- Nous allons devoir manipuler les hyperparamètres du modèle pour corriger le problème
- GridSearch

In [ ]:
model = SVR()

print("Résultat SVR")
modele_validation(model, X, y)

# faire un scaling

Avec ENERGYSTARScore

                    R2       MAE      RMSE  Time (sec)
Train (Fit)  -0.017587  0.421763  0.562451    0.125864
Test (Score) -0.030675  0.425526  0.564128    0.048186

Sans ENERGYSTARScore

                    R2      MAE      RMSE  Time (sec)
Train (Fit)  -0.017526  0.42177  0.562434    0.111481
Test (Score) -0.030555  0.42552  0.564094    0.048668

### Optimisation d'un modèle

### Comparaison de différents modèles supervisés

A réaliser :
* Pour chaque algorithme que vous allez tester, vous devez :
    * Réaliser au préalable une séparation en jeu d'apprentissage et jeu de test via une validation croisée.
    * Si les features quantitatives que vous souhaitez utiliser ont des ordres de grandeur très différents les uns des autres, et que vous utilisez un algorithme de regression qui est sensible à cette différence, alors il faut réaliser un scaling (normalisation) de la donnée au préalable.
    * Entrainer le modèle sur le jeu de Train
    * Prédire la cible sur la donnée de test (nous appelons cette étape, l'inférence).
    * Calculer les métriques de performance R2, MAE et RMSE sur le jeu de train et de test.
    * Interpréter les résultats pour juger de la fiabilité de l'algorithme.
* Vous pouvez choisir par exemple de tester un modèle linéaire, un modèle à base d'arbres et un modèle de type SVM
* Déterminer le modèle le plus performant parmi ceux testés.

In [15]:
# CODE COMPARAISON DES MODELES

### Optimisation et interprétation du modèle

A réaliser :
* Reprennez le meilleur algorithme que vous avez sécurisé via l'étape précédente, et réalisez une GridSearch de petite taille sur au moins 3 hyperparamètres.
* Si le meilleur modèle fait partie de la famille des modèles à arbres (RandomForest, GradientBoosting) alors utilisez la fonctionnalité feature importance pour identifier les features les plus impactantes sur la performance du modèle. Sinon, utilisez la méthode Permutation Importance de sklearn.

In [16]:
# CODE OPTIMISATION ET INTERPRETATION DU MODELE